name: cdac_design
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.0-323.0.dev

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  convex_bottom_bar: ^3.2.0
  phone_state: ^1.0.4
  phone_state_background: ^0.0.4
  call_log: ^4.0.0
  permission_handler: ^11.3.1
  intl: ^0.19.0
  contacts_service: ^0.6.3
  flutter_local_notifications: ^17.2.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
